name: CI - Tests

on:
  pull_request:
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  test:
    name: .NET unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore Dashboard.sln

      - name: Build
        run: dotnet build Dashboard.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Dashboard.sln --configuration Release --no-build --no-restore
