name: CI - Tests

on:
  pull_request:
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  NODE_VERSION: '20.19.0'

jobs:
  test:
    name: .NET unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore Dashboard.sln

      - name: Build
        run: dotnet build Dashboard.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Dashboard.sln --configuration Release --no-build --no-restore

  frontend-tests:
    name: Frontend unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dashboardfrontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: dashboardfrontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run React unit tests
        run: npm test
